### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by seisman** [gmt-china/gmt-china.org#2]
- [x] 增加复制代码的按钮
  - http://matcornic.github.io/hugo-learn-doc/basics/what-is-this-hugo-theme/
  - https://clipboardjs.com/
- [x] 增加 notice, note, info, warning 等提示语
  - https://matcornic.github.io/hugo-learn-doc/cont/shortcodes/
  - http://v3.bootcss.com/components/#alerts
- [x] GMT 示例的开头增加脚本、数据的下载链接
- [x] CSS, HTML, JS 压缩
- [x] 制作新 LOGO
- [ ] 自定义GMT语法高亮，使得博文中的代码可以高亮GMT相关的部分
  - http://prismjs.com/#tutorials
  - http://asarosenberg.se/code/extending-and-customizing-prism-syntax-highlighter/
- [x] 是否要增加一个FAQ页面或FAQ网站？
  - http://themes.gohugo.io/theme/hugo-faq-theme/ 
- [ ] 自动检测网站中所有链接的有效性
- [ ] 脚本的开头写上脚本对应的GMT版本以及是bash还是bat？
- [ ] 脚本以GMT5的bash脚本为主，如果不满足该条件，则需要加note
- [ ] 自动压缩图片尺寸
- [ ] 图片大小自适应
- [ ] 博文列表页面使用了 .PrevInSection 和 .NextInSection，因而只能看到当前 section 的博文。如何解决？是否要在博文列表中将一般博文与示例博文区分开？
- [x] 增加评论功能
- [ ] 404页面
- [ ] sitemap页面
